/**
 * Single structured source of truth for Egypt's administrative divisions.
 * Governorate -> its own cities / centers (marakez) / districts.
 *
 * Rules kept by this dataset:
 *  - Every governorate carries its complete relevant list.
 *  - A center appears under exactly one governorate.
 *  - No duplicates inside a governorate.
 *  - Arabic is the canonical value (teacher records store Arabic names);
 *    English exists for localization only.
 *
 * To extend: add an entry to EGYPT_GOVERNORATES — nothing else needs to change.
 */

export type LocalizedName = { ar: string; en: string };

export type GovernorateEntry = LocalizedName & {
  districts: LocalizedName[];
};

const d = (ar: string, en: string): LocalizedName => ({ ar, en });

export const EGYPT_GOVERNORATES: GovernorateEntry[] = [
  {
    ar: "القاهرة",
    en: "Cairo",
    districts: [
      d("وسط البلد", "Downtown"),
      d("عابدين", "Abdeen"),
      d("الأزبكية", "Azbakeya"),
      d("باب الشعرية", "Bab El Sheereya"),
      d("الموسكي", "Mouski"),
      d("الجمالية", "Gamaleya"),
      d("الدرب الأحمر", "Darb El Ahmar"),
      d("الخليفة", "El Khalifa"),
      d("السيدة زينب", "Sayeda Zeinab"),
      d("مصر القديمة", "Old Cairo"),
      d("المنيل", "Manial"),
      d("الزمالك", "Zamalek"),
      d("جاردن سيتي", "Garden City"),
      d("بولاق", "Boulaq"),
      d("شبرا", "Shubra"),
      d("روض الفرج", "Rod El Farag"),
      d("الشرابية", "Sharabeya"),
      d("الساحل", "El Sahel"),
      d("الزاوية الحمراء", "Zawya El Hamra"),
      d("حدائق القبة", "Hadayek El Kobba"),
      d("الوايلي", "Waily"),
      d("الظاهر", "El Zaher"),
      d("مدينة نصر", "Nasr City"),
      d("مصر الجديدة", "Heliopolis"),
      d("النزهة", "Nozha"),
      d("الماظة", "Almaza"),
      d("الزيتون", "Zeitoun"),
      d("عين شمس", "Ain Shams"),
      d("المطرية", "Matareya"),
      d("المرج", "El Marg"),
      d("السلام", "El Salam"),
      d("الأميرية", "Amireya"),
      d("منشية ناصر", "Manshiyet Nasser"),
      d("المقطم", "Mokattam"),
      d("البساتين", "Basateen"),
      d("دار السلام", "Dar El Salam"),
      d("المعادي", "Maadi"),
      d("طرة", "Tura"),
      d("المعصرة", "Maasara"),
      d("حلوان", "Helwan"),
      d("15 مايو", "15th of May City"),
      d("التبين", "Tebeen"),
      d("حدائق حلوان", "Hadayek Helwan"),
      d("القاهرة الجديدة / التجمع", "New Cairo / Tagamoa"),
      d("الرحاب", "Al Rehab"),
      d("مدينتي", "Madinaty"),
      d("مدينة الشروق", "Shorouk City"),
      d("مدينة بدر", "Badr City"),
      d("العاصمة الإدارية الجديدة", "New Administrative Capital"),
    ],
  },
  {
    ar: "الجيزة",
    en: "Giza",
    districts: [
      d("الدقي", "Dokki"),
      d("العجوزة", "Agouza"),
      d("المهندسين", "Mohandessin"),
      d("إمبابة", "Imbaba"),
      d("الوراق", "Warraq"),
      d("بولاق الدكرور", "Boulaq El Dakrour"),
      d("العمرانية", "Omraneya"),
      d("الهرم", "Haram"),
      d("فيصل", "Faisal"),
      d("المنيب", "Moneeb"),
      d("حدائق الأهرام", "Hadayek El Ahram"),
      d("أوسيم", "Ossim"),
      d("كرداسة", "Kerdasa"),
      d("منشأة القناطر", "Manshiyet El Qanater"),
      d("أبو النمرس", "Abu Al Nomros"),
      d("البدرشين", "Badrashin"),
      d("الحوامدية", "Hawamdeya"),
      d("الصف", "El Saff"),
      d("أطفيح", "Atfih"),
      d("العياط", "Ayat"),
      d("6 أكتوبر", "6th of October City"),
      d("الشيخ زايد", "Sheikh Zayed"),
      d("الواحات البحرية", "Bahareya Oasis"),
    ],
  },
  {
    ar: "الإسكندرية",
    en: "Alexandria",
    districts: [
      d("المنشية", "Manshiya"),
      d("محطة الرمل", "Mahatet El Raml"),
      d("الأنفوشي", "Anfoushi"),
      d("رأس التين", "Ras El Tin"),
      d("الجمرك", "Gomrok"),
      d("اللبان", "Labban"),
      d("كرموز", "Karmouz"),
      d("محرم بك", "Moharam Bek"),
      d("الحضرة", "Hadra"),
      d("الإبراهيمية", "Ibrahimeya"),
      d("كامب شيزار", "Camp Caesar"),
      d("الشاطبي", "Shatby"),
      d("سيدي جابر", "Sidi Gaber"),
      d("سموحة", "Smouha"),
      d("كفر عبده", "Kafr Abdo"),
      d("رشدي", "Roushdy"),
      d("جليم", "Gleem"),
      d("سان ستيفانو", "San Stefano"),
      d("زيزينيا", "Zizinia"),
      d("بولكلي", "Bolkly"),
      d("لوران", "Louran"),
      d("سيدي بشر", "Sidi Bishr"),
      d("ميامي", "Miami"),
      d("العصافرة", "Asafra"),
      d("المندرة", "Mandara"),
      d("المعمورة", "Maamoura"),
      d("أبو قير", "Abu Qir"),
      d("المنتزه", "Montaza"),
      d("فلمنج", "Fleming"),
      d("باكوس", "Bacos"),
      d("العجمي", "Agami"),
      d("الدخيلة", "Dekheila"),
      d("المكس", "Max"),
      d("الورديان", "Wardian"),
      d("العامرية", "Ameriya"),
      d("برج العرب", "Borg El Arab"),
      d("برج العرب الجديدة", "New Borg El Arab"),
    ],
  },
  {
    ar: "القليوبية",
    en: "Qalyubia",
    districts: [
      d("بنها", "Banha"),
      d("قليوب", "Qalyub"),
      d("شبرا الخيمة", "Shubra El Kheima"),
      d("الخصوص", "Khosous"),
      d("الخانكة", "Khanka"),
      d("القناطر الخيرية", "Qanater El Khayreya"),
      d("طوخ", "Toukh"),
      d("قها", "Qaha"),
      d("كفر شكر", "Kafr Shukr"),
      d("شبين القناطر", "Shibin El Qanater"),
      d("العبور", "Obour City"),
    ],
  },
  {
    ar: "المنوفية",
    en: "Monufia",
    districts: [
      d("شبين الكوم", "Shibin El Kom"),
      d("منوف", "Menouf"),
      d("سرس الليان", "Sers El Layan"),
      d("أشمون", "Ashmoun"),
      d("الباجور", "Bagour"),
      d("قويسنا", "Quesna"),
      d("بركة السبع", "Berket El Sabe"),
      d("تلا", "Tala"),
      d("الشهداء", "El Shohada"),
      d("مدينة السادات", "Sadat City"),
    ],
  },
  {
    ar: "الغربية",
    en: "Gharbia",
    districts: [
      d("طنطا", "Tanta"),
      d("المحلة الكبرى", "El Mahalla El Kubra"),
      d("كفر الزيات", "Kafr El Zayat"),
      d("زفتى", "Zefta"),
      d("السنطة", "El Santa"),
      d("قطور", "Qutur"),
      d("بسيون", "Basyoun"),
      d("سمنود", "Samannoud"),
    ],
  },
  {
    ar: "الدقهلية",
    en: "Dakahlia",
    districts: [
      d("المنصورة", "Mansoura"),
      d("طلخا", "Talkha"),
      d("ميت غمر", "Mit Ghamr"),
      d("دكرنس", "Dekernes"),
      d("أجا", "Aga"),
      d("السنبلاوين", "Sinbillawin"),
      d("منية النصر", "Menyet El Nasr"),
      d("بلقاس", "Belqas"),
      d("شربين", "Sherbin"),
      d("المطرية", "Matareya"),
      d("المنزلة", "Manzala"),
      d("ميت سلسيل", "Mit Salsil"),
      d("الجمالية", "Gamaliya"),
      d("بني عبيد", "Bani Ubaid"),
      d("تمي الأمديد", "Tami El Amdid"),
      d("نبروه", "Nabaroh"),
      d("محلة دمنة", "Mahallat Damana"),
      d("جمصة", "Gamasa"),
      d("المنصورة الجديدة", "New Mansoura"),
    ],
  },
  {
    ar: "الشرقية",
    en: "Sharqia",
    districts: [
      d("الزقازيق", "Zagazig"),
      d("العاشر من رمضان", "10th of Ramadan City"),
      d("بلبيس", "Bilbeis"),
      d("منيا القمح", "Minya El Qamh"),
      d("مشتول السوق", "Mashtoul El Souk"),
      d("القنايات", "Qenayat"),
      d("أبو حماد", "Abu Hammad"),
      d("القرين", "El Qurein"),
      d("ههيا", "Hehia"),
      d("أبو كبير", "Abu Kebir"),
      d("فاقوس", "Faqous"),
      d("الحسينية", "Husseiniya"),
      d("ديرب نجم", "Diyarb Negm"),
      d("كفر صقر", "Kafr Saqr"),
      d("أولاد صقر", "Awlad Saqr"),
      d("الإبراهيمية", "Ibrahimiya"),
      d("الصالحية الجديدة", "New Salhia"),
      d("صان الحجر", "San El Hagar"),
      d("منشأة أبو عمر", "Manshiyet Abu Omar"),
    ],
  },
  {
    ar: "كفر الشيخ",
    en: "Kafr El Sheikh",
    districts: [
      d("كفر الشيخ", "Kafr El Sheikh"),
      d("دسوق", "Desouk"),
      d("فوه", "Fuwwah"),
      d("مطوبس", "Metoubes"),
      d("بيلا", "Biyala"),
      d("الرياض", "El Reyad"),
      d("قلين", "Qallin"),
      d("سيدي سالم", "Sidi Salem"),
      d("الحامول", "El Hamool"),
      d("بلطيم", "Baltim"),
      d("برج البرلس", "Borg El Borollos"),
    ],
  },
  {
    ar: "البحيرة",
    en: "Beheira",
    districts: [
      d("دمنهور", "Damanhour"),
      d("كفر الدوار", "Kafr El Dawwar"),
      d("رشيد", "Rosetta"),
      d("إدكو", "Edku"),
      d("أبو المطامير", "Abu El Matamir"),
      d("أبو حمص", "Abu Homs"),
      d("الدلنجات", "Delengat"),
      d("المحمودية", "Mahmoudiya"),
      d("الرحمانية", "Rahmaniya"),
      d("إيتاي البارود", "Itay El Barud"),
      d("حوش عيسى", "Hosh Issa"),
      d("شبراخيت", "Shubrakhit"),
      d("كوم حمادة", "Kom Hamada"),
      d("بدر", "Badr"),
      d("وادي النطرون", "Wadi El Natrun"),
      d("النوبارية الجديدة", "New Nubaria"),
    ],
  },
  {
    ar: "الإسماعيلية",
    en: "Ismailia",
    districts: [
      d("الإسماعيلية", "Ismailia"),
      d("فايد", "Fayed"),
      d("القنطرة شرق", "Qantara East"),
      d("القنطرة غرب", "Qantara West"),
      d("التل الكبير", "Tell El Kebir"),
      d("أبو صوير", "Abu Suweir"),
      d("القصاصين الجديدة", "New Qassasin"),
    ],
  },
  {
    ar: "بورسعيد",
    en: "Port Said",
    districts: [
      d("الشرق", "El Sharq"),
      d("العرب", "El Arab"),
      d("المناخ", "El Manakh"),
      d("الضواحي", "El Dawahi"),
      d("الزهور", "El Zohour"),
      d("الجنوب", "El Ganoub"),
      d("بورفؤاد", "Port Fouad"),
    ],
  },
  {
    ar: "السويس",
    en: "Suez",
    districts: [
      d("السويس", "Suez"),
      d("الأربعين", "Arbaeen"),
      d("عتاقة", "Ataqa"),
      d("الجناين", "Ganayen"),
      d("فيصل", "Faisal"),
    ],
  },
  {
    ar: "دمياط",
    en: "Damietta",
    districts: [
      d("دمياط", "Damietta"),
      d("دمياط الجديدة", "New Damietta"),
      d("رأس البر", "Ras El Bar"),
      d("فارسكور", "Faraskur"),
      d("الزرقا", "El Zarqa"),
      d("السرو", "El Sarw"),
      d("الروضة", "El Rawda"),
      d("كفر سعد", "Kafr Saad"),
      d("كفر البطيخ", "Kafr El Battikh"),
      d("عزبة البرج", "Ezbet El Borg"),
    ],
  },
  {
    ar: "شمال سيناء",
    en: "North Sinai",
    districts: [
      d("العريش", "Arish"),
      d("الشيخ زويد", "Sheikh Zuweid"),
      d("رفح", "Rafah"),
      d("بئر العبد", "Bir El Abd"),
      d("الحسنة", "Hasana"),
      d("نخل", "Nakhl"),
credit    ],
  },
  {
    ar: "جنوب سيناء",
    en: "South Sinai",
    districts: [
      d("الطور", "El Tor"),
      d("شرم الشيخ", "Sharm El Sheikh"),
      d("دهب", "Dahab"),
      d("نويبع", "Nuweiba"),
      d("طابا", "Taba"),
      d("سانت كاترين", "Saint Catherine"),
      d("أبو رديس", "Abu Rudeis"),
      d("أبو زنيمة", "Abu Zenima"),
      d("رأس سدر", "Ras Sedr"),
    ],
  },
  {
    ar: "البحر الأحمر",
    en: "Red Sea",
    districts: [
      d("الغردقة", "Hurghada"),
      d("رأس غارب", "Ras Ghareb"),
      d("سفاجا", "Safaga"),
      d("القصير", "Quseer"),
      d("مرسى علم", "Marsa Alam"),
      d("الشلاتين", "Shalateen"),
      d("حلايب", "Halayeb"),
    ],
  },
  {
    ar: "مطروح",
    en: "Matrouh",
    districts: [
      d("مرسى مطروح", "Marsa Matrouh"),
      d("الحمام", "El Hammam"),
      d("العلمين", "El Alamein"),
      d("الضبعة", "Dabaa"),
      d("النجيلة", "Negeila"),
      d("سيدي براني", "Sidi Barrani"),
      d("السلوم", "Salloum"),
      d("سيوة", "Siwa"),
    ],
  },
  {
    ar: "الوادي الجديد",
    en: "New Valley",
    districts: [
      d("الخارجة", "Kharga"),
      d("الداخلة", "Dakhla"),
      d("الفرافرة", "Farafra"),
      d("باريس", "Paris"),
      d("بلاط", "Balat"),
    ],
  },
  {
    ar: "الفيوم",
    en: "Fayoum",
    districts: [
      d("الفيوم", "Fayoum"),
      d("الفيوم الجديدة", "New Fayoum"),
      d("سنورس", "Sinnuris"),
      d("إطسا", "Etsa"),
      d("إبشواي", "Ibsheway"),
      d("طامية", "Tamiya"),
      d("يوسف الصديق", "Youssef El Seddik"),
    ],
  },
  {
    ar: "بني سويف",
    en: "Beni Suef",
    districts: [
      d("بني سويف", "Beni Suef"),
      d("بني سويف الجديدة", "New Beni Suef"),
      d("الواسطى", "El Wasta"),
      d("ناصر", "Nasser"),
      d("إهناسيا", "Ihnasia"),
      d("ببا", "Biba"),
      d("سمسطا", "Somosta"),
      d("الفشن", "El Fashn"),
    ],
  },
  {
    ar: "المنيا",
    en: "Minya",
    districts: [
      d("المنيا", "Minya"),
      d("المنيا الجديدة", "New Minya"),
      d("العدوة", "El Adwa"),
      d("مغاغة", "Maghagha"),
      d("بني مزار", "Beni Mazar"),
      d("مطاي", "Matay"),
      d("سمالوط", "Samalut"),
      d("أبو قرقاص", "Abu Qurqas"),
      d("ملوي", "Mallawi"),
      d("دير مواس", "Deir Mawas"),
    ],
  },
  {
    ar: "أسيوط",
    en: "Assiut",
    districts: [
      d("أسيوط", "Assiut"),
      d("أسيوط الجديدة", "New Assiut"),
      d("ديروط", "Dairut"),
      d("القوصية", "Qusiya"),
      d("منفلوط", "Manfalut"),
      d("أبنوب", "Abnub"),
      d("الفتح", "El Fath"),
      d("أبو تيج", "Abu Tig"),
      d("صدفا", "Sedfa"),
      d("البداري", "Badari"),
      d("ساحل سليم", "Sahel Selim"),
      d("الغنايم", "El Ghanayem"),
    ],
  },
  {
    ar: "سوهاج",
    en: "Sohag",
    districts: [
      d("سوهاج", "Sohag"),
      d("سوهاج الجديدة", "New Sohag"),
      d("أخميم", "Akhmim"),
      d("البلينا", "El Balyana"),
      d("المراغة", "Maragha"),
      d("المنشاة", "El Monshah"),
      d("دار السلام", "Dar El Salam"),
      d("جرجا", "Girga"),
      d("جهينة", "Gohaina"),
      d("ساقلتة", "Saqultah"),
      d("طما", "Tama"),
      d("طهطا", "Tahta"),
    ],
  },
  {
    ar: "قنا",
    en: "Qena",
    districts: [
      d("قنا", "Qena"),
      d("قنا الجديدة", "New Qena"),
      d("أبو تشت", "Abu Tesht"),
      d("نجع حمادي", "Nag Hammadi"),
      d("دشنا", "Deshna"),
      d("الوقف", "El Waqf"),
      d("قفط", "Qift"),
      d("قوص", "Qus"),
      d("نقادة", "Naqada"),
      d("فرشوط", "Farshut"),
    ],
  },
  {
    ar: "الأقصر",
    en: "Luxor",
    districts: [
      d("الأقصر", "Luxor"),
      d("الأقصر الجديدة", "New Luxor"),
      d("إسنا", "Esna"),
      d("أرمنت", "Armant"),
      d("الطود", "El Tod"),
      d("الزينية", "El Zeiniya"),
      d("البياضية", "El Bayadiya"),
      d("القرنة", "El Qurna"),
    ],
  },
  {
    ar: "أسوان",
    en: "Aswan",
    districts: [
      d("أسوان", "Aswan"),
      d("أسوان الجديدة", "New Aswan"),
      d("دراو", "Daraw"),
      d("كوم أمبو", "Kom Ombo"),
      d("نصر النوبة", "Nasr El Nuba"),
      d("كلابشة", "Kalabsha"),
      d("إدفو", "Edfu"),
      d("الرديسية", "El Radisiya"),
      d("البصيلية", "El Basiliya"),
      d("السباعية", "El Sibaiya"),
      d("أبو سمبل السياحية", "Abu Simbel"),
    ],
  },
];

/** Arabic governorate name -> entry (canonical lookup). */
const GOV_BY_AR = new Map(EGYPT_GOVERNORATES.map((g) => [g.ar, g]));

export function getGovernorate(ar: string): GovernorateEntry | undefined {
  return GOV_BY_AR.get(ar);
}

/** Districts for a governorate (Arabic key). Empty array when unknown. */
export function getDistricts(governorateAr: string): LocalizedName[] {
  return GOV_BY_AR.get(governorateAr)?.districts ?? [];
}

export function governorateLabel(ar: string, lang: "ar" | "en"): string {
  const g = GOV_BY_AR.get(ar);
  return lang === "en" ? (g?.en ?? ar) : ar;
}

export function districtLabel(
  governorateAr: string,
  districtAr: string,
  lang: "ar" | "en",
): string {
  if (lang === "ar") return districtAr;
  const match = getDistricts(governorateAr).find((x) => x.ar === districtAr);
  return match?.en ?? districtAr;
}

/** Backwards-compatible flat map: governorate (ar) -> district names (ar). */
export const GOVERNORATES_AR: Record<string, string[]> = Object.fromEntries(
  EGYPT_GOVERNORATES.map((g) => [g.ar, g.districts.map((x) => x.ar)]),
);
